import dataclasses

_fields = {
    'id': int,
    'start_anim': int,
    'anim_id': int,
    'head_ef': int,
    'chest_ef': int,
    'base_ef': int,
    'lefthand_ef': int,
    'righthand_ef': int,
    'breath_ef': int,
    'leftweapon_ef': int,
    'rightweapon_ef': int,
    'special_ef1': int,
    'special_ef2': int,
    'special_ef3': int,
    'special_ef4': int,
    'world_ef': int,
    'sound_id': int,
    'shake_id': int,
    'char_proc1': int,
    'char_proc2': int,
    'char_proc3': int,
    'char_proc4': int,
    'char_param_zero1': float,
    'char_param_zero2': float,
    'char_param_zero3': float,
    'char_param_zero4': float,
    'char_param_one1': float,
    'char_param_one2': float,
    'char_param_one3': float,
    'char_param_one4': float,
    'char_param_two1': float,
    'char_param_two2': float,
    'char_param_two3': float,
    'char_param_two4': float,
    'char_param_three1': float,
    'char_param_three2': float,
    'char_param_three3': float,
    'char_param_three4': float,
}

SpellVisualKitRecord = dataclasses.make_dataclass('SpellVisualKitRecord', zip(_fields.keys(), _fields.values()))
SpellVisualKitRecord.field_types = staticmethod(_fields.values())
